//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggingService.WCFClient.WCFLogger {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFLogger.IWCFLogger")]
    public interface IWCFLogger {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFLogger/LogInfo", ReplyAction="http://tempuri.org/IWCFLogger/LogInfoResponse")]
        void LogInfo(string appName, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFLogger/LogError", ReplyAction="http://tempuri.org/IWCFLogger/LogErrorResponse")]
        void LogError(string appName, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFLogger/LogWarning", ReplyAction="http://tempuri.org/IWCFLogger/LogWarningResponse")]
        void LogWarning(string appName, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFLogger/LogErrorWithException", ReplyAction="http://tempuri.org/IWCFLogger/LogErrorWithExceptionResponse")]
        void LogErrorWithException(string appName, string message, System.Exception ex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFLoggerChannel : LoggingService.WCFClient.WCFLogger.IWCFLogger, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFLoggerClient : System.ServiceModel.ClientBase<LoggingService.WCFClient.WCFLogger.IWCFLogger>, LoggingService.WCFClient.WCFLogger.IWCFLogger {
        
        public WCFLoggerClient() {
        }
        
        public WCFLoggerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFLoggerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFLoggerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFLoggerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void LogInfo(string appName, string message) {
            base.Channel.LogInfo(appName, message);
        }
        
        public void LogError(string appName, string message) {
            base.Channel.LogError(appName, message);
        }
        
        public void LogWarning(string appName, string message) {
            base.Channel.LogWarning(appName, message);
        }
        
        public void LogErrorWithException(string appName, string message, System.Exception ex) {
            base.Channel.LogErrorWithException(appName, message, ex);
        }
    }
}
